apiVersion: v1
kind: ConfigMap
metadata:
  name: sapliy-fintech-config
  labels:
    app: sapliy-fintech
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  DATABASE_URL: "postgres://sapliy:sapliy123@postgresql:5432/sapliy?sslmode=disable"
  REDIS_URL: "redis://redis-master:6379"
  KAFKA_BROKERS: "kafka:9092"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  PAYMENTS_SERVICE_URL: "http://payments-service:8082"
  LEDGER_SERVICE_URL: "http://ledger-service:8083"